### PR TITLE
Implement the "top_match" configuration parameter

### PR DESCRIPTION
**Pull request by Unholny**
Hey guys,

On behalf of our team and clients that use your API - big thank you!
We decided to help you out with a quick implementation of the "top_match" search configuration parameter.

Kind regards,
Martin Dinkov,
Sitewab Ltd.

### CODE REVIEW

**Comment by Unholny** [comment]
@yuri1992 any news? I would like to be able to install it on my client's production server without messing around with the vendor folder.

**Comment by melkayam92** [comment]
Hey @Unholny ,

Thank you for your contribution!

We will check it and let you know in a few days.

**Comment by Unholny** [comment]
Thank you very much!
Merry Christmas!

**Comment by Unholny** [comment]
Hey @melkayam92 @yuri1992 ,

I would like to kindly remind you of the pending updates that I have suggested to the Pipl API PHP Package. What's the estimated time of implementing them into your library?

Kind Regards,
Martin Dinkov,
Sitewab Ltd.

**Pull request merged**
